### PR TITLE
Use C++ math functions

### PR DESCRIPTION
**Pull request by vloncar**
This solves the synthesis process hanging when we use static tables.

### CODE REVIEW

**Comment by benjaminkreis** [comment]
Unfortunately this doesn't look like a fix.  I'm getting bad latency and interval results for the sigmoid:

```
        +---------------------------------+-----------------------+-----+-----+-----+-----+----------+
        |                                 |                       |  Latency  |  Interval | Pipeline |
        |             Instance            |         Module        | min | max | min | max |   Type   |
        +---------------------------------+-----------------------+-----+-----+-----+-----+----------+
        |grp_compute_layer_0_0_0_s_fu_79  |compute_layer_0_0_0_s  |    2|    2|    1|    1| function |
        |grp_sigmoid_fu_85                |sigmoid                |    4|  515|    4|  515|   none   |
        |grp_compute_layer_0_0_fu_94      |compute_layer_0_0      |    2|    2|    1|    1| function |
        |call_ret1_relu_fu_131            |relu                   |    0|    0|    1|    1| function |
        +---------------------------------+-----------------------+-----+-----+-----+-----+----------+

```

**Comment by vloncar** [comment]
I get the same numbers since the introduction of static tables. If I remove the static qualifier but keep the cmath changes the latency goes back to ~10

**Comment by benjaminkreis** [comment]
Ok I think we need to take a closer look at that static PR

**Comment by nhanvtran** [comment]
Thanks all, ok can we roll back on the static PR, @zhenbinwu @vloncar?  My fault for merging it too soon.  We're working on some unit tests as the project grows...

**Comment by zhenbinwu** [comment]
The static problem and the csim issue can be fixed like below:
```
#ifdef __HLS_SYN__
    bool initialized = false;
    typename CONFIG_T::table_t sigmoid_table[CONFIG_T::table_size];
#else
    static bool initialized = false;
    static typename CONFIG_T::table_t sigmoid_table[CONFIG_T::table_size];
#endif
```

No my favorite style, but it solved both issues. @vloncar @benjaminkreis Can you double check?

**Comment by vloncar** [comment]
@zhenbinwu I am not sure how this would work. If the table is not static during synthesis (`#ifdef __HLS_SYN__`), the code essentially behaves in the same way as before the change was introduced, right? It would simply be reinitialized every time. Or am I missing something?

**Comment by zhenbinwu** [comment]
@vloncar There was an issue with csim in vivado_hls v2018.2. The initiation of the LUT takes a very long time. We introduced the static variables to avoid multiple initiation. Now I just split out the csim and syn steps in the code. BTW, can you check the csim speed after you change to std::exp()?  Maybe it got fixed?

**Comment by vloncar** [comment]
@zhenbinwu The speed is the same, as C++ compiler essentially does the same thing and only a workaround for HLS. There is another option, using `hls_math.h` and using its functions (e.g., `hls::exp()`), but this significantly increases the compilation time of csim (like 4-5 minutes), so I didn't use it. It also doesn't solve the problem with latency.

**Comment by benjaminkreis** [comment]
Regarding the HLS Math Library -- this would be to evaluate the exp() in real time with FPGA logic rather than by precomputing a lookup table.  I think we want to stick with the lookup table approach.

**Comment by zhenbinwu** [comment]
What do you mean the speed is the same? With std::exp(), the original code csim with 1layer is still slow.

**Comment by vloncar** [comment]
There should be no difference between `std:exp()` from `cmath` and `exp()` from `math.h`. The latter one exists for the compatibility with C, and the former is the C++ way, but the underlying math is the same. My guess is that HLS synthesis gets confused somehow, it sees `exp()`, which accepts `double`, yet we give it `float`, does the type promotion, blows up memory usage, and hangs. 

Since this PR doesn't fix the problem with latency, I would suggest we close it without merging.

**Comment by nhanvtran** [comment]
hi all,  ok, i tried to get a summary from @benjaminkreis and @zhenbinwu 

In short, adding the static blows up the csynth time and the resource usage, but without the static, the csim time is super slow.  So we will close this PR and @zhenbinwu is going to make a new PR which has the solution along the lines of what he posted above:

```
#ifdef __HLS_SYN__
    bool initialized = false;
    typename CONFIG_T::table_t sigmoid_table[CONFIG_T::table_size];
#else
    static bool initialized = false;
    static typename CONFIG_T::table_t sigmoid_table[CONFIG_T::table_size];
#endif
```

**Pull request closed without merging**
