### PR TITLE
Fix two issues for the concatenate layer

### PR DESCRIPTION
**Pull request by melko**

### CODE REVIEW

**Comment by vloncar** [comment]
Awesome!
Do you have an example model which demonstrates the improvement? Like a minimal example...

**Comment by melko** [comment]
Hi,
I saw the issue on a model I'm trying, which implements several convolutional layer, then concatenating outputs before a dense layer. I can share that one or, if you prefer, I can make a minimal example with just a concat layer.

**Comment by vloncar** [comment]
I would prefer a minimal example because we can include it in the future test suite (currently being revamped). You can just share a code gist somewhere, that would be fine

**Comment by melko** [comment]
Here's a minimal example. which concatenates an input with itself:
https://gist.github.com/melko/51411e1f952038dfaadd4669ad960388

**Pull request merged**
